parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.6'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
            # this is needed because of Doctrine... https://github.com/symfony/symfony-docs/issues/6398
            row_format: DYNAMIC

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Quiz:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CoreBundle/Quiz/Entity'
                prefix: 'CoreBundle\Quiz'
                alias: Quiz
            Section:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CoreBundle/Quiz/Entity'
                prefix: 'CoreBundle\Section'
                alias: Section
            Question:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CoreBundle/Quiz/Entity'
                prefix: 'CoreBundle\Question'
                alias: Question
            Answer:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CoreBundle/Quiz/Entity'
                prefix: 'CoreBundle\Answer'
                alias: Answer
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CoreBundle/User/Entity'
                prefix: 'CoreBundle\User'
                alias: User
