version: '3'

services:
    php:
      build:
        context: ./docker/php
        dockerfile: Dockerfile
        args:
          HOST_USER_ID: ${HOST_USER_ID}
          HOST_GROUP_ID: ${HOST_GROUP_ID}

      volumes:
        - ./:/var/www
      links:
        - database

    database:
      build:
        context: ./docker/database
        dockerfile: Dockerfile
      ports:
        - 33066:3306
      volumes:
        - ./var/docker/mysql-files:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: greymane420
        MYSQL_DATABASE: kvizomat


    web_server:
      build:
        context: ./docker/web_server
        dockerfile: Dockerfile
      volumes:
        - ./:/var/www
        - ./var/docker/web_server:/var/logs
      environment:
        DOMAINS: "${APP_DOMAIN} www.${APP_DOMAIN}"
      links:
        - php
      depends_on:
        - php

    node:
      build:
        context: ./docker/node
        dockerfile: Dockerfile
      volumes:
        - ./:/var/www




