# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  core.doctrine.user_listener:
    class: CoreBundle\Listeners\UserListener
    autowire: true
    tags:
        - { name: doctrine.event_subscriber }

  core.security.login_authenticator:
    class: CoreBundle\Security\LoginAuthenticator
    autowire: true